#!/bin/bash

# 微信消息实体函数
_msgBodys(){
local int AppID=1000002
local UserID=$1
local Msg="$2"
cat << EOF
{
"touser": "${UserID}",
"msgtype": "text",
"agentid": "${AppID}",
"text": {
"content": "${Msg}"
},
"safe": "0"
}
EOF
}

#发送消息函数
_sendMsgs(){
CropID='ww89xxxxxxxf1f14'
Secret='axnLxvxxxxxxxoB9xxxxx9Z_mNPY' 
GET_URL="https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=${CropID}&corpsecret=${Secret}"
Gtoken=$(/usr/bin/curl -s -G $GET_URL| grep -Po "(?<=access_token\W{3})[\w-]+")
POST_URL="https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=${Gtoken}"
/usr/bin/curl -s -k --data-ascii "$(_msgBodys "$1" "$2")" $POST_URL
}


#发送从zabbix传过来的消息
sendUser=$1
sendContent="$2 $3"
_sendMsgs $sendUser "$sendContent"

